#*****************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# create_pulpus.tcl: Tcl script for re-creating project 'ro2-system'
#
# Generated by Vivado on Tue Nov 20 23:27:49 +0100 2018
# IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_pulpus.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set project_name "ro2-system"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set project_name $::user_project_name
}

variable script_file
set script_file "create_pulpus.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set project_name [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "./ro2-system"]"

# Create project
create_project ${project_name} ./${project_name} -part xc7s50csga324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${project_name}.cache/ip" -objects $obj
set_property -name "part" -value "xc7s50csga324-1" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/pulpus_lib/fpga_defines.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/dc_full_detector.v"]"\
 "[file normalize "$origin_dir/pulpus_lib/dc_synchronizer.v"]"\
 "[file normalize "$origin_dir/pulpus_lib/dc_token_ring.v"]"\
 "[file normalize "$origin_dir/pulpus_lib/dc_token_ring_fifo_din.v"]"\
 "[file normalize "$origin_dir/pulpus_lib/dc_token_ring_fifo_dout.v"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulpus.v"]"\
 "[file normalize "$origin_dir/pulpus_lib/AddressDecoder_Req_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/AddressDecoder_Req_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/AddressDecoder_Resp_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/AddressDecoder_Resp_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/ArbitrationTree_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/ArbitrationTree_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/FanInPrimitive_Req_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/FanInPrimitive_Req_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/FanInPrimitive_Resp_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/FanInPrimitive_Resp_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/MUX2_REQ_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/MUX2_REQ_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/RR_Flag_Req_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/RR_Flag_Req_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/RequestBlock1CH_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/RequestBlock2CH_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/RequestBlock_L2_1CH.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/RequestBlock_L2_2CH.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/ResponseBlock_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/ResponseBlock_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/ResponseTree_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/ResponseTree_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/XBAR_BRIDGE.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/XBAR_L2.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/adv_timer_apb_if.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/apb2per.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/apb_adv_timer.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/apb_fll_if.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/apb_gpio.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/apb_interrupt_cntrl.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/apb_node.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/apb_node_wrap.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/apb_soc_ctrl.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/apb_timer_unit.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/axi64_2_lint32.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/axi_ar_buffer.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/axi_aw_buffer.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/axi_b_buffer.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/axi_r_buffer.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/axi_read_ctrl.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/axi_w_buffer.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/axi_write_ctrl.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulp_soc_defines.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/boot_rom.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/cluster_clock_gating_xilinx.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/comparator.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/dc_data_buffer.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/edge_propagator_rx.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/fc_demux.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/fc_hwpe.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/soc_bus_defines.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/fc_subsystem.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/generic_fifo.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_ctrl_interfaces.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_ctrl_package.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_ctrl_regfile.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_ctrl_regfile_latch.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_ctrl_slave.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_ctrl_ucode.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_package.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_addressgen.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_fifo.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_fifo_scm.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_interfaces.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_merge.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_sink.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_sink_realign.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_source.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_source_realign.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_split.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/hwpe_stream_tcdm_fifo_store.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/input_stage.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/io_generic_fifo.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/io_tx_fifo.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/jtag_wrapper.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/l2_ram_multi_bank.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/l2_tcdm_demux.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/lint64_to_32.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/lint_2_apb.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/mac_package.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/mac_ctrl.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/mac_engine.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/mac_fsm.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/mac_streamer.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/mac_top.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/mac_top_wrap.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/memory_models.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/onehot_to_bin.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pad_control.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pad_frame.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pad_functional_xilinx.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/periph_bus_defines.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/periph_bus_wrap.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/prescaler.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulp_clk_sync_wedge_fpga.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulp_clock_gating_async.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulp_clock_gating_xilinx.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulp_interfaces.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulp_soc.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulp_sync_wedge.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulpissimo.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pulpissimo_emu.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/register_file_3r_2w_be.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/rstgen.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/safe_domain.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/scm_2048x32.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/soc_clk_rst_gen.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/soc_domain.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/soc_event_arbiter.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/soc_event_generator.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/soc_event_queue.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/soc_interconnect.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/soc_interconnect_wrap.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/soc_peripherals.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/timer_cntrl.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/timer_module.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/timer_unit_counter.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_apb_if.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_arbiter.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_ch_addrgen.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_core.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_ctrl.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_dc_fifo.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_rx_channels.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_subsystem.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_tx_channels.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_uart_reg_if.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_uart_rx.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_uart_top.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/udma_uart_tx.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/up_down_counter.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/xilinx_memory.sv"]"\
 "[file normalize "$origin_dir/pulpus_lib/pri1.mem"]"\
 "[file normalize "$origin_dir/pulpus_lib/boot-pulpissimo.mem"]"\
 "[file normalize "$origin_dir/pulpus_lib/vga_digilent.vhd"]"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "pulpus_lib/pri1.mem"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "pulpus_lib/boot-pulpissimo.mem"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "pulpus_lib/fpga_defines.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj
set_property -name "is_global_include" -value "1" -objects $file_obj

set file "pulpus_lib/AddressDecoder_Req_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/AddressDecoder_Req_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/AddressDecoder_Resp_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/AddressDecoder_Resp_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/ArbitrationTree_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/ArbitrationTree_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/FanInPrimitive_Req_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/FanInPrimitive_Req_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/FanInPrimitive_Resp_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/FanInPrimitive_Resp_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/MUX2_REQ_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/MUX2_REQ_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/RR_Flag_Req_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/RR_Flag_Req_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/RequestBlock1CH_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/RequestBlock2CH_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/RequestBlock_L2_1CH.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/RequestBlock_L2_2CH.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/ResponseBlock_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/ResponseBlock_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/ResponseTree_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/ResponseTree_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/XBAR_BRIDGE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/XBAR_L2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/adv_timer_apb_if.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/apb2per.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/apb_adv_timer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/apb_fll_if.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/apb_gpio.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/apb_interrupt_cntrl.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/apb_node.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/apb_node_wrap.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/apb_soc_ctrl.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/apb_timer_unit.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/axi64_2_lint32.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/axi_ar_buffer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/axi_aw_buffer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/axi_b_buffer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/axi_r_buffer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/axi_read_ctrl.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/axi_w_buffer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/axi_write_ctrl.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pulp_soc_defines.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "pulpus_lib/boot_rom.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/cluster_clock_gating_xilinx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/comparator.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/dc_data_buffer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/edge_propagator_rx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/fc_demux.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/fc_hwpe.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/soc_bus_defines.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "pulpus_lib/fc_subsystem.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/generic_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_ctrl_interfaces.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_ctrl_package.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_ctrl_regfile.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_ctrl_regfile_latch.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_ctrl_slave.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_ctrl_ucode.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_package.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_addressgen.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_fifo_scm.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_interfaces.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_merge.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_sink.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_sink_realign.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_source.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_source_realign.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_split.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/hwpe_stream_tcdm_fifo_store.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/input_stage.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/io_generic_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/io_tx_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/jtag_wrapper.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/l2_ram_multi_bank.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/l2_tcdm_demux.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/lint64_to_32.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/lint_2_apb.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/mac_package.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/mac_ctrl.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/mac_engine.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/mac_fsm.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/mac_streamer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/mac_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/mac_top_wrap.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/memory_models.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/onehot_to_bin.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pad_control.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pad_frame.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pad_functional_xilinx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/periph_bus_defines.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "pulpus_lib/periph_bus_wrap.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/prescaler.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pulp_clk_sync_wedge_fpga.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pulp_clock_gating_async.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pulp_clock_gating_xilinx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pulp_interfaces.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pulp_soc.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pulp_sync_wedge.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pulpissimo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/pulpissimo_emu.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/register_file_3r_2w_be.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/rstgen.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/safe_domain.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/scm_2048x32.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/soc_clk_rst_gen.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/soc_domain.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/soc_event_arbiter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/soc_event_generator.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/soc_event_queue.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/soc_interconnect.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/soc_interconnect_wrap.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/soc_peripherals.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/timer_cntrl.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/timer_module.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/timer_unit_counter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_apb_if.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_arbiter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_ch_addrgen.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_core.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_ctrl.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_dc_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_rx_channels.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_subsystem.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_tx_channels.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_uart_reg_if.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_uart_rx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_uart_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/udma_uart_tx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/up_down_counter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/xilinx_memory.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "pulpus_lib/vga_digilent.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset properties
#set obj [get_filesets sources_1]
#set_property -name "top" -value "top" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/pulpus_lib/ip/jtag_axi_0/jtag_axi_0.xci"]"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
#set obj [get_filesets sources_1]
# Import local files from the original project
#set files [list \
 "[file normalize "$origin_dir/../pulpus.xpr/pulpus/pulpus-Kopie/pulpus.srcs/sources_1/ip/vio_0/vio_0.xci"]"\
]
#set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
#set file "vio_0/vio_0.xci"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "is_enabled" -value "0" -objects $file_obj


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/pulpus_lib/ip/proc_sys_reset_0/proc_sys_reset_0.xci"]"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
#set obj [get_filesets sources_1]
# Import local files from the original project
#set files [list \
# "[file normalize "$origin_dir/../pulpus.xpr/pulpus/pulpus-Kopie/pulpus.srcs/sources_1/ip/vio_1/vio_1.xci"]"\
#]
#set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
#set file "vio_1/vio_1.xci"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "is_enabled" -value "0" -objects $file_obj


# Set 'sources_1' fileset object
#set obj [get_filesets sources_1]
# Import local files from the original project
#set files [list \
# "[file normalize "$origin_dir/../pulpus.xpr/pulpus/pulpus-Kopie/pulpus.srcs/sources_1/ip/vio_2/vio_2.xci"]"\
#]
#set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
#set file "vio_2/vio_2.xci"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "is_enabled" -value "0" -objects $file_obj


# Set 'sources_1' fileset object
#set obj [get_filesets sources_1]
# Import local files from the original project
#set files [list \
# "[file normalize "$origin_dir/../pulpus.xpr/pulpus/pulpus-Kopie/pulpus.srcs/sources_1/ip/vio_3/vio_3.xci"]"\
#]
#set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
#set file "vio_3/vio_3.xci"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "is_enabled" -value "0" -objects $file_obj


# Set 'sources_1' fileset object
#set obj [get_filesets sources_1]
# Import local files from the original project
#set files [list \
# "[file normalize "$origin_dir/../pulpus.xpr/pulpus/pulpus-Kopie/pulpus.srcs/sources_1/ip/vio_4/vio_4.xci"]"\
#]
#set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
#set file "vio_4/vio_4.xci"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "is_enabled" -value "0" -objects $file_obj


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/pulpus_lib/constraints.xdc"]"
set file_imported [import_files -fileset constrs_1 $file]
set file "pulpus_lib/constraints.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/pulpus_lib/io.xdc"]"
set file_imported [import_files -fileset constrs_1 $file]
set file "pulpus_lib/io.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
#set obj [get_filesets sim_1]
# Import local files from the original project
#set files [list \
# "[file normalize "$origin_dir/../pulpus.xpr/pulpus/pulpus-Kopie/pulpus.srcs/sim_1/imports/pulpus/timer.wcfg"]"\
#]
#set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
#set obj [get_filesets sim_1]
#set_property -name "top" -value "top" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7s50csga324-1 -flow {Vivado Synthesis 2017} -strategy "Flow_RuntimeOptimized" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Flow_RuntimeOptimized" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7s50csga324-1" -objects $obj
set_property -name "strategy" -value "Flow_RuntimeOptimized" -objects $obj
set_property -name "steps.synth_design.args.flatten_hierarchy" -value "none" -objects $obj
set_property -name "steps.synth_design.args.directive" -value "RuntimeOptimized" -objects $obj
set_property -name "steps.synth_design.args.fsm_extraction" -value "off" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7s50csga324-1 -flow {Vivado Implementation 2017} -strategy "Flow_RuntimeOptimized" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Flow_RuntimeOptimized" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7s50csga324-1" -objects $obj
set_property -name "strategy" -value "Flow_RuntimeOptimized" -objects $obj
set_property -name "steps.opt_design.args.directive" -value "RuntimeOptimized" -objects $obj
set_property -name "steps.place_design.args.directive" -value "RuntimeOptimized" -objects $obj
set_property -name "steps.route_design.args.directive" -value "RuntimeOptimized" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:$project_name"
