`define PULP_FPGA_EMUL 1
`define DISABLE_JTAG_TAP_TOP
`define DISABLE_CLUSTER
`define DISABLE_JTAG_WRAPPER
`define REDUCE_PERIPHS
`define REDUCE_PERIPHS_LINT
`define ONE_HWPE_PORT
`define NO_UDMA_FILTER
`define NO_TO_CLUSTER_AXI
`define NO_ADV_TIMER
//`define DISABLE_UNUSED_MEM